server:
  port: 8080

spring:
  application:
    name: geoportail-resina-backend
  profiles:
    active: dev

resina:
  message: "Configuration de base (aucun profil specifique)"
  netxms-sync:
    enabled: true
    sites-cron: "0 0 2 * * *"
    equipments-cron: "0 15 2 * * *"