server:
  port: 8080

spring:
  application:
    name: geoportail-resina-backend
  profiles:
    active: dev
  flyway:
    enabled: true
    schemas: geoportail_resina
    default-schema: geoportail_resina
    baseline-on-migrate: true
    baseline-version: 0

resina:
  message: "Configuration de base (aucun profil specifique)"
  netxms-sync:
    enabled: true
    sites-cron: "0 0 2 * * *"
    equipments-cron: "0 15 2 * * *"