resina:
  message: "Profil DEV actif - vous etes en local"
  access-token: "dev-token"
  rate-limit-capacity: 50000

  netxms:
    base-url: "http://localhost:8080/mock-netxms"
    bearer-token: "dev-token"

  bootstrap:
    admin-login: ${RESINA_BOOTSTRAP_ADMIN_LOGIN:admin.dest}
    admin-password: ${RESINA_BOOTSTRAP_ADMIN_PASSWORD:ChangeMe123!}
    admin-nom-complet: ${RESINA_BOOTSTRAP_ADMIN_NOM:Administrateur ANPTIC}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geoportail_resina_db?currentSchema=geoportail_resina
    username: postgres
    password: admin@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: geoportail_resina
        # dialect: retirable, Hibernate le détecte automatiquement (voir warning HHH90000025 dans vos logs)

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Africa/Ouagadougou

resina-netxms:
  datasource:
    url: jdbc:postgresql://localhost:5432/netxmsdb?currentSchema=donnebase,equipementinfastructure,public
    username: geoportail_readonly
    password: ${RESINA_NETXMS_DB_PASSWORD:UnNouveauMotDePasseSolide!2026}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.security: DEBUG

server:
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always